name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your branch is named differently

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Upload the entire repository root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
